language: go

env:
  # encrypted form of COVERALLS_TOKEN API key
  - secure: "Ok3RNguO3Ar1ItaLMS5XwOfPFwUcgdpyUwQAejvf/4NFCEm9xTsaMxS7xQaKJ5LZ+leS9ulgFbITqY+r2kdPhjWI/SUsP15KtDWnaIqrVjahuTYkGmK2N72VvmNXX3nGj6PUBjTb7/IMJWraPI/iKF2t39NfQCiBLTP9V66wiReB6P2R8NlP9BuXzwtOktwkaZc/yKy01xXlz+ZbpoLfYpg0+RH94aN9g4E7467D01KLgwSsiP3FsPcKEYmlG9AuxzRNeKdTGZiVJqj96VFdBYgLiLFQnlEF/avBeyPP/Nz8vJFJRJQuX0yW7gyKA2pUCqfPVogRbwp3WexJHOlTOCC65fxl/N7x9w94muTFEjjZ9ALz+xPToVSiNkw/zYTdqTAJP04AKGDsvmGZMqPPuK8wLqUzVMkQmfYmLLYBlzNHhLsinZBFYtqnL95NJ/SLGvVfIJuJ3HzMM2LGvt+0LWgVFNymx3atap3kPhjEUVs/9+FBNcu1gRAjttQg6evYJmSMw3Iijr6riJgVPTMjTJWGVUchCLmO9hVefxfvAysbUxyajaKCYBtYq+jBDkAnGQ4ztq5aL1W0b3CXSs2YlVRMoKEmznzCWJXIMR3IFbtaeHEoeky/mqzkCF3vX2JfLHQ+VL9OQokdnC1Ammds3SwuXLku9+PIzl9rXzhxziI="

go:
  - 1.10.x

before_install:
  - go get github.com/sirupsen/logrus
  - go get github.com/brutella/can
  - go get github.com/google/go-cmp/cmp
  - go get github.com/gorilla/mux
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  # upload coverage.out report
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - make install

deploy:
  provider: releases
  api_key:
    secure: "Bw6uqasy6W8aFW/idrgvCjPt/HPD/VtTfyvaciOLYKLh7WGumhC6z+zN2knPkSFjrF3B/0WOjfoOcxTNBDTSxq8IUrhvQgrD2tgPx+9zXvy0Ch1DKhUpNPdiis7VM/O5fG9Uq7dylV5XrPmlwqFOkTl/xTk3fKH7lVDOSX07bTnHwdvFkpRBH8RwhWuYqmtJKmfK1CYGN1wc8FekjADGPI7YrZa3ccNyDyNLU4JH4qjLibIWvY7p5GJHMR8K9MhD585fUB6l0WK3ZMezf1GyTs7TehqvwUhIdt6BphA28UNTkHu82k4Jy/1zZlrImLhjxLT+AAInVW/Utjlze4IDSlBR2dAhm50G7tzec2BgNhxrMRV/BzpPMK7HLwE9ehXwZr2THEggRIBLyKQVkqfDdEDLezL77/cCzR7lpuY8L0l35XEOPCw8765QAhZDhbIQvivycJlEyV30fN/UaPtgoBDIHLLIbM4zF+ljzyHCoHSzKiS/Dr9vss03V5Ojbtq7MV1o6rcwcuuTk/PjNffAA5WgPmTm9hfe2qsov5IlgtMcagVoEDq5InFurUmMLtlyZO9wJAkhRho4Fnfny6y9lsKU/UJvPMZtGfvo732g9WGj1k7wuqHobR7hh2Dz3ZoIqlLbjj+BW3A4c0DLGp0ORFm6J99GoAvut8lbrGd3ou4="
  file: "dist/lgresu-*-linux-*.tar.gz"
  file_glob: "true"
  skip_cleanup: true
  on:
    tags: true
    
